version: "3"
services:
  ma6-mini:
    image: 2swo/ma6-mini-movie
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: always
    environment:
      - TZ=Asia/Seoul
    volumes:
      - /Users/2swo/애자일/MA6/6term-mini-back-movie/app:/home/app
